#!/usr/bin/python3

import numpy as np
from scipy.linalg import block_diag

# Constants
hbar = 6.582E-16 # 6.582 * 10^-16 [eV*s]
c = 2.998E8 # 2.998 * 10^8 [m/s]
q = 1.602E-19 # [C]
m_e = 0.51E6 / c**2 # [MeV/c^2]
pi = np.pi

# System parameters
a = 0.246E-9 # [m] lattice constant for graphene
m = m_e # [MeV/c^2]
v_f = 1E6 # [m/s] fermi velocity for graphene
h = v_f*hbar/a # [eV] hopping energy for graphene based on formula? This value is close to the 2.8 eV
h = 2.8 # [eV] hopping energy for graphene is 2.8 eV
k = pi/(4*a) # [m^-1] Momentum space wavenumber Probably shouldn't be zero for graphene
ka = k*a

# Laser parameters
hw = 191e-3 # [meV]
Estrength = 5e7 # V/m
d = 120E-9 # [m] Spatial period of the electric field of laser in x direction, make sure d>>a and not necessarily integer multiple
K = 2*pi/d # Spatial wavenumber of laser light in x direction

# Matrix cutoffs
# Number of modes
mc = 2
Nm = 2*mc+1
nhw = np.arange(-mc,mc+1,1)

# Size of system in x direction
rc = 4
xm = rc*a
Nr = 2*rc+1
xj = np.linspace(-xm, xm, Nr)

phimin = 0
phimax = 1e9 # unitless
phimax = Estrength*a/hw # unitless

nphi = 100
phi0 = np.linspace(phimin,phimax,nphi)
#energy = np.zeros( (Nm*Nr, nphi) )
energy = np.zeros( (4*Nr, nphi) )
H = np.zeros( (Nm,4*Nr,4*Nr) , dtype='complex')

# Build global arrays for time domain fourier transform
tau = np.linspace(0, 2*pi, 51)
s1 = np.sin(tau)
c2 = np.cos(2*tau)

def create_H_n(_n, _phi, _ka):
  hjla1b1 = -h* np.trapz(np.exp(1.0j * _phi * (-np.sqrt(3)/2 * np.outer(np.ones(Nr),s1) + 0.25 * np.outer(np.sin(np.sqrt(3)*K*(xj+a/4)), c2) - _n*tau) ), x=tau) / (2*pi)
  hjlb1a2 = -h* np.trapz(np.exp(1.0j * _phi * (0.5 * np.outer(np.sin(np.sqrt(3)*K*(xj+a/2)), c2) -_n*tau) ), x=tau) / (2*pi)
  hjla2b2 = -h* np.trapz(np.exp(1.0j * _phi * (-np.sqrt(3)/2 * np.outer(np.ones(Nr),s1) + 0.25 * np.outer(np.sin(np.sqrt(3)*K*(xj+3*a/4)), c2) - _n*tau) ), x=tau) / (2*pi)

  hjp1lb1a1 = -h* np.trapz(np.exp(1.0j * _phi * (-np.sqrt(3)/2 * np.outer(np.ones(Nr),s1) - 0.25 * np.outer(np.sin(np.sqrt(3)*K*(xj+3*a/4)), c2) - _n*tau) ), x=tau) / (2*pi)
  hjp1lb2a2 = -h* np.trapz(np.exp(1.0j * _phi * (-np.sqrt(3)/2 * np.outer(np.ones(Nr),s1) - 0.25 * np.outer(np.sin(np.sqrt(3)*K*(xj+5*a/4)), c2) - _n*tau) ), x=tau) / (2*pi)
  hjp1lp1b2a1 = -h* np.trapz(np.exp(1.0j * _phi * (0.5 * np.outer(np.sin(np.sqrt(3)*K*(xj+a)), c2) - 3*_ka - _n*tau) ), x=tau) / (2*pi)

  Hb = np.zeros((4*Nr,4*Nr), dtype='complex')

  for xidx, xval in enumerate(xj):
    Hb[4*xidx:4*(xidx+1),4*xidx:4*(xidx+1)] = np.array([[0,hjla1b1[xidx],0,0],[0,0,hjlb1a2[xidx],0],[0,0,0,hjla2b2[xidx]],[0,0,0,0]])
  for xidx, xval in enumerate(xj[:-1]):
    Hb[4*xidx:4*(xidx+1),4*(xidx+1):4*(xidx+2)] = np.array([[0,0,0,0],[hjp1lb1a1[xidx],0,0,0],[0,0,0,0],[hjp1lp1b2a1[xidx],0,hjp1lb2a2[xidx],0]])

  Hb = Hb + Hb.conj().T
  return Hb


# For loop over the phi0 terms
for i, phi in enumerate(phi0):

  # Calculate individual block matrices for given phi0 and construct Q matrix
  # Clear the Q matrix since we will be adding to the matrix
  Q = np.zeros( (Nm*4*Nr,Nm*4*Nr) , dtype = 'complex')
  for n in range(Nm):
    # To construct the H_n matrices we must numerically solve the time domain Fourier transform for each matrix index
    H[n] = create_H_n(n, phi, ka)

    # Quick way to fill the Q matrix is to use kronecker functions for the block diagonals (and subdiagonals H_1, H_2, ...)
    Q += np.kron(np.diag(np.ones(Nm-n),k=-n),H[n])

  # Quickly apply the modes along the diagonal of Q
  Q += np.kron(np.diag(nhw,k=0),np.eye(4*Nr))

  eng = np.linalg.eigvalsh(Q, UPLO = 'L')
  energy[:,i] = eng[(mc+0)*4*Nr:(mc+1)*4*Nr]


np.savetxt('./data/eng-matrix.txt', energy, fmt='%1.8f')


